# fly.toml app configuration file for cryptopop-sniper background worker
app = 'cryptopop-sniper'
primary_region = 'arn'

[build]

[env]

[processes]
  app = "python sol_sniper_bot.py"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[restart]]
  policy = "always"

[experimental]
  auto_rollback = false

[deploy]
  strategy = "immediate"
