# fly.toml app configuration file generated for cryptopop-sniper on 2025-07-25T11:32:11Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cryptopop-sniper'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[processes]
app = "python sol_sniper_bot.py"

[experimental]
auto_rollback = false

[deploy]
strategy = "immediate"

